import React from "react";
import {
	Modal,
	ModalContent,
	ModalHeader,
	ModalBody,
	ModalFooter,
	Button,
	useDisclosure,
	Link,
} from "@nextui-org/react";

const FooterSection: React.FC = () => {
	const modalTerms = useDisclosure();
	const modalPolicy = useDisclosure();

	const renderModal = (
		title: string,
		content: React.ReactNode,
		isOpen: boolean,
		onOpenChange: () => void
	) => (
		<Modal
			size="xl"
			isOpen={isOpen}
			onOpenChange={onOpenChange}
			scrollBehavior="inside"
		>
			<ModalContent>
				{(onClose) => (
					<>
						<ModalHeader className="flex flex-col gap-1">
							{title}
						</ModalHeader>
						<ModalBody className="text-justify">
							{content}
						</ModalBody>
						<ModalFooter>
							<Button
								color="danger"
								variant="light"
								onPress={onClose}
							>
								Close
							</Button>
						</ModalFooter>
					</>
				)}
			</ModalContent>
		</Modal>
	);

	return (
		<div className="flex flex-col items-center justify-center w-full p-8 bg-zinc-800 text-white">
			<div className="flex flex-col md:flex-row md:space-x-48 items-center md:items-start justify-center w-full max-w-6xl">
				<div className="flex flex-col items-center md:items-start text-center md:text-left space-y-4 max-w-lg">
					<div className="text-xl font-bold hover:opacity-90">
						<Link href="/" className="text-white">🎯Goooooals</Link>
					</div>
					<div className="text-sm md:text-base">
						Discover your most meaningful goal
					</div>
					<div className="text-sm md:text-base text-gray-400">
						Whether you need a nudge or a structured plan, Goooooals
						provides tailored goal suggestions and detailed
						breakdowns to help you stay motivated and on track.
					</div>
				</div>
				<div className="flex flex-col items-center md:items-start text-center md:text-left space-y-4 mt-8 md:mt-0">
					<div className="text-lg font-semibold">Links</div>
					<div className="text-sm">
						<Link
							onPress={modalTerms.onOpen}
							className="cursor-pointer text-white hover:underline"
						>
							Terms of Service
						</Link>
						{renderModal(
							"Terms of Service",
							<>
								<p>
									<i>Effective Date: October 12, 2024</i>
								</p>
								<hr />
								<p>
									Welcome to Goooooals! By accessing or using
									our web app, you agree to comply with and be
									bound by the following Terms of Service.
									Please read these terms carefully before
									using our services. These terms were
									prepared with the assistance of ChatGPT.
								</p>
								<br />
								<h2>1. Acceptance of Terms</h2>
								<p>
									By using Goooooals, you agree to these Terms
									of Service and our Privacy Policy. If you do
									not agree with any part of these terms, you
									should not use our web app.
								</p>
								<br />
								<h2>2. Services Provided</h2>
								<p>
									Goal Generation: Goooooals provides a
									platform for generating, customizing, and
									receiving details about personal goals. We
									use external APIs and tools to generate goal
									suggestions based on your input.
								</p>
								<p>
									Email Communication: We collect your email
									address solely to send goal details and
									related updates. We do not store or retain
									your email address beyond this purpose.
								</p>
								<br />
								<h2>3. Disclaimer and Limitations</h2>
								<p>
									Reference Only: The goals generated by
									Goooooals are for reference and inspiration
									purposes only. They are not guaranteed to be
									suitable, effective, or relevant for your
									personal situation. We encourage you to
									conduct your own research and consider
									seeking professional advice before pursuing
									any goals suggested by our platform.
								</p>
								<p>
									No Obligation of Reliability: Goooooals
									makes no representations or warranties
									regarding the accuracy, reliability, or
									suitability of the goals generated. We do
									not guarantee that the goals will meet your
									specific needs or expectations. You use the
									generated goals at your own risk and should
									not rely solely on the information provided
									by Goooooals.
								</p>
								<br />
								<h2>4. User Responsibilities</h2>
								<p>
									Accuracy of Information: You are responsible
									for providing accurate information when
									using the goal generation tools and ensuring
									that any input provided is true and correct.
								</p>
								<p>
									Use of Service: You agree to use Goooooals
									for lawful purposes and in accordance with
									these Terms of Service. You must not use the
									web app in any way that may harm or disrupt
									our services or the experience of other
									users.
								</p>
								<br />
								<h2>5. Intellectual Property</h2>
								<p>
									Ownership: All content, features, and
									functionality of Goooooals, including but
									not limited to text, graphics, logos, and
									software, are the property of Goooooals or
									its licensors and are protected by
									intellectual property laws.
								</p>
								<p>
									Restrictions: You may not reproduce,
									duplicate, copy, sell, resell, or exploit
									any portion of our web app without express
									written permission from Goooooals.
								</p>
								<br />
								<h2>6. Limitation of Liability</h2>
								<p>
									Disclaimer: Goooooals provides its services
									“as is” and makes no representations or
									warranties of any kind, express or implied,
									regarding the accuracy, reliability, or
									availability of the services.
								</p>
								<p>
									Limitation of Liability: To the fullest
									extent permitted by law, Goooooals shall not
									be liable for any indirect, incidental,
									special, consequential, or punitive damages
									arising out of or in connection with your
									use of the web app.
								</p>
								<br />
								<h2>7. Termination</h2>
								<p>
									We reserve the right to suspend or terminate
									your access to Goooooals at our sole
									discretion if we believe you have violated
									these Terms of Service or for any other
									reason.
								</p>
								<br />
								<h2>8. Changes to Terms</h2>
								<p>
									We may update these Terms of Service from
									time to time to reflect changes in our
									practices or legal requirements. The updated
									terms will be posted on this page with the
									revised effective date. Your continued use
									of the web app after such changes
									constitutes your acceptance of the new
									terms.
								</p>
								<br />
								<h2>9. Contact Us</h2>
								<p>
									If you have any questions or concerns about
									these Terms of Service, please contact us
									through GitHub.
								</p>
							</>,
							modalTerms.isOpen,
							modalTerms.onOpenChange
						)}
					</div>
					<div className="text-sm">
						<Link
							onPress={modalPolicy.onOpen}
							className="cursor-pointer text-white hover:underline"
						>
							Privacy Policy
						</Link>
						{renderModal(
							"Privacy Policy",
							<>
								<p>
									<i>Effective Date: October 12, 2024</i>
								</p>
								<hr />
								<p>
									At Goooooals, we prioritize your privacy and
									are committed to protecting your personal
									information. This Privacy Policy outlines
									how we collect, use, and protect your email
									address and explains our practices regarding
									data handling. These terms were prepared
									with the assistance of ChatGPT.
								</p>
								<br />
								<h2>1. Information We Collect</h2>
								<p>
									We collect your email address solely for the
									purpose of sending you details of the goals
									you generate and any related updates or
									reminders. You provide your email address
									voluntarily when you choose to receive goal
									details and updates.
								</p>
								<br />
								<h2>2. How We Use Your Information</h2>
								<p>
									We use your email address exclusively to
									send you goal details and any follow-up
									updates or reminders related to your goals.
									Your email address is used only for this
									purpose and is not stored or retained after
									the email is sent.
								</p>
								<br />
								<h2>3. Data Security</h2>
								<p>
									We implement reasonable measures to ensure
									that your email address is handled securely
									during the transmission process. However, we
									do not store email addresses on our servers
									or in our system.
								</p>
								<br />
								<h2>4. Data Retention</h2>
								<p>
									Your email address is not stored or retained
									in our web app. Once we have sent the goal
									details to your email address, it is deleted
									from our system.
								</p>
								<br />
								<h2>5. Third-Party Services</h2>
								<p>
									We may use third-party email delivery
									services to send goal details and updates.
									These services are selected for their
									reliability and security and are
									contractually bound to handle your email
									address confidentially and only for the
									purpose of sending the requested
									information.
								</p>
								<br />
								<h2>6. Your Rights</h2>
								<p>
									If you prefer not to receive emails, you may
									choose not to provide your email address or
									contact us to request that no further emails
									be sent. As we do not store your email
									address, we cannot provide access or
									corrections to it. However, you can contact
									us if you have any concerns.
								</p>
								<br />
								<h2>7. Changes to This Privacy Policy</h2>
								<p>
									We may update this Privacy Policy
									periodically to reflect changes in our
									practices. Any changes will be posted on
									this page with the updated effective date.
									We encourage you to review this policy
									periodically.
								</p>
								<br />
								<h2>8. Contact Us</h2>
								<p>
									If you have any questions or concerns about
									this Privacy Policy or how we handle your
									email address, please contact us through
									GitHub
								</p>
							</>,
							modalPolicy.isOpen,
							modalPolicy.onOpenChange
						)}
					</div>
					<div className="text-sm">
						<Link
							href="https://github.com/nicholaslhq/goooooals"
							isExternal
							className="cursor-pointer text-white hover:underline"
						>
							GitHub
						</Link>
					</div>
				</div>
			</div>
			<div className="mt-16 text-sm text-center w-full max-w-6xl">
				<div className="flex justify-center">
					<div>
						Made by&nbsp;
						<Link
							href="https://github.com/nicholaslhq/"
							isExternal
							className="cursor-pointer text-white hover:underline text-sm"
						>
							Nicholas Lee
						</Link>
					</div>
				</div>
			</div>
		</div>
	);
};

export default FooterSection;
